allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@vercel/backends@7.0.2'
  - '@vercel/build-utils@14.9.1'
  - '@vercel/cervel@0.1.61'
  - '@vercel/container@7.0.1'
  - '@vercel/elysia@7.0.1'
  - '@vercel/express@7.0.2'
  - '@vercel/fastify@7.0.1'
  - '@vercel/gatsby-plugin-vercel-builder@2.2.53'
  - '@vercel/go@10.0.1'
  - '@vercel/h3@7.0.1'
  - '@vercel/hono@7.0.1'
  - '@vercel/hydrogen@8.0.1'
  - '@vercel/koa@7.0.1'
  - '@vercel/nestjs@7.0.1'
  - '@vercel/next@11.0.2'
  - '@vercel/node@12.0.1'
  - '@vercel/python@13.0.1'
  - '@vercel/redwood@9.0.1'
  - '@vercel/remix-builder@12.0.1'
  - '@vercel/ruby@9.0.1'
  - '@vercel/rust@8.0.1'
  - '@vercel/static-build@9.0.1'
  - '@vercel/vc-native-darwin-arm64@59.11.7'
  - '@vercel/vc-native-darwin-x64@59.11.7'
  - '@vercel/vc-native-linux-arm64@59.11.7'
  - '@vercel/vc-native-linux-x64@59.11.7'
  - vercel@59.11.7
