// Display metadata only; availability comes from the safe catalog.
export const ADMIN_DATA_CATEGORIES = [
  {
    id: 'content',
    title: '教學內容',
    description: '從課程架構找到教材，再查題目與發布紀錄。',
  },
  {
    id: 'learning',
    title: '學習與評量',
    description: '依學習活動找紀錄；各入口維持既有授權與遮罩。',
  },
  {
    id: 'classroom',
    title: '班級與 Live',
    description: '查閱既有班級與 Live 紀錄；不增加跨班級學生支援。',
  },
  {
    id: 'rewards',
    title: '獎勵與收藏',
    description: '先找獎勵種類，再查帳本或持有紀錄；金額與獎勵維持後端決定。',
  },
  {
    id: 'users',
    title: '帳號資料',
    description: '此處只查閱帳號資料。建立教師或重設密碼仍在「教師帳號」入口。',
  },
] as const;
export const ADMIN_DATA_LABELS: Record<
  string,
  { category: string; group: string; title: string; description: string }
> = {
  courses: {
    category: 'content',
    group: '課程架構',
    title: '課程',
    description: '有哪些課程與基本設定',
  },
  chapters: {
    category: 'content',
    group: '課程架構',
    title: '章',
    description: '課程內的章與排列',
  },
  sections: {
    category: 'content',
    group: '課程架構',
    title: '節',
    description: '每章下的教學小節',
  },
  subtopics: {
    category: 'content',
    group: '課程架構',
    title: '知識主題',
    description: '小節內的知識主題分類',
  },
  review_cards: {
    category: 'content',
    group: '複習教材',
    title: '複習卡',
    description: '複習卡內容與所屬教材',
  },
  review_card_media: {
    category: 'content',
    group: '複習教材',
    title: '教材圖片與媒體',
    description: '複習卡使用的媒體紀錄',
  },
  questions: {
    category: 'content',
    group: '題目與活動',
    title: '題目',
    description: '題目的受控資料與分類',
  },
  question_options: {
    category: 'content',
    group: '題目與活動',
    title: '題目選項',
    description: '題目對應的選項紀錄',
  },
  question_hints: {
    category: 'content',
    group: '題目與活動',
    title: '題目提示',
    description: '題目所使用的提示紀錄',
  },
  quiz_templates: {
    category: 'content',
    group: '題目與活動',
    title: '測驗模板',
    description: '測驗的組成與設定紀錄',
  },
  external_activities: {
    category: 'content',
    group: '題目與活動',
    title: '外部活動',
    description: '課程使用的外部活動紀錄',
  },
  content_imports: {
    category: 'content',
    group: '匯入與上線紀錄',
    title: '內容匯入',
    description: '匯入批次與處理紀錄',
  },
  content_versions: {
    category: 'content',
    group: '匯入與上線紀錄',
    title: '內容版本',
    description: '已建立的內容版本紀錄',
  },
  content_publication_events: {
    category: 'content',
    group: '匯入與上線紀錄',
    title: '發布歷程',
    description: '內容的發布事件與紀錄',
  },
  review_progress: {
    category: 'learning',
    group: '複習與補救',
    title: '複習進度',
    description: '已記錄的複習活動進度',
  },
  mistake_items: {
    category: 'learning',
    group: '複習與補救',
    title: '錯題紀錄',
    description: '需要複習的錯題紀錄',
  },
  remediation_attempts: {
    category: 'learning',
    group: '複習與補救',
    title: '補救練習',
    description: '補救活動的嘗試紀錄',
  },
  hint_events: {
    category: 'learning',
    group: '複習與補救',
    title: '提示使用',
    description: '一般學習提示的使用事件',
  },
  quiz_sessions: {
    category: 'learning',
    group: '測驗與作答',
    title: '測驗場次',
    description: '測驗活動與其狀態紀錄',
  },
  quiz_session_questions: {
    category: 'learning',
    group: '測驗與作答',
    title: '測驗出題',
    description: '每場測驗所使用的題目紀錄',
  },
  quiz_answers: {
    category: 'learning',
    group: '測驗與作答',
    title: '測驗作答',
    description: '測驗已提交的作答紀錄',
  },
  assignments: {
    category: 'learning',
    group: '作業紀錄',
    title: '作業',
    description: '已建立的作業設定',
  },
  assignment_targets: {
    category: 'learning',
    group: '作業紀錄',
    title: '作業指派',
    description: '作業的既有指派對象紀錄',
  },
  assignment_attempts: {
    category: 'learning',
    group: '作業紀錄',
    title: '作業作答',
    description: '作業的嘗試與完成紀錄',
  },
  mastery_sessions: {
    category: 'learning',
    group: '精熟挑戰',
    title: '精熟挑戰場次',
    description: '章末精熟挑戰的場次紀錄',
  },
  mastery_attempts: {
    category: 'learning',
    group: '精熟挑戰',
    title: '精熟挑戰作答',
    description: '精熟挑戰的嘗試紀錄',
  },
  mastery_hint_events: {
    category: 'learning',
    group: '精熟挑戰',
    title: '精熟提示使用',
    description: '精熟挑戰內的提示事件',
  },
  classrooms: {
    category: 'classroom',
    group: '既有班級查閱',
    title: '班級',
    description: '既有受控班級資料',
  },
  classroom_members: {
    category: 'classroom',
    group: '既有班級查閱',
    title: '班級成員紀錄',
    description: '既有受控成員關係紀錄',
  },
  live_sessions: {
    category: 'classroom',
    group: 'Live 場次與參與',
    title: 'Live 場次',
    description: '即時活動場次與狀態紀錄',
  },
  live_participants: {
    category: 'classroom',
    group: 'Live 場次與參與',
    title: 'Live 參與紀錄',
    description: '場次中已記錄的參與情形',
  },
  live_activities: {
    category: 'classroom',
    group: 'Live 場次與參與',
    title: 'Live 活動',
    description: '即時活動的內容設定紀錄',
  },
  live_session_questions: {
    category: 'classroom',
    group: 'Live 題目與作答',
    title: 'Live 出題',
    description: '即時場次使用的題目紀錄',
  },
  live_answers: {
    category: 'classroom',
    group: 'Live 題目與作答',
    title: 'Live 作答',
    description: '即時場次已提交的作答紀錄',
  },
  live_join_throttle: {
    category: 'classroom',
    group: '加入問題查核',
    title: 'Live 加入限制',
    description: '查核加入活動的限流紀錄',
  },
  xp_transactions: {
    category: 'rewards',
    group: '經驗值與代幣',
    title: '經驗值流水',
    description: '經驗值的異動紀錄',
  },
  wallet_transactions: {
    category: 'rewards',
    group: '經驗值與代幣',
    title: '代幣流水',
    description: '代幣的收入與支出紀錄',
  },
  wallets: {
    category: 'rewards',
    group: '經驗值與代幣',
    title: '代幣帳戶',
    description: '既有代幣帳戶資料',
  },
  blooks: {
    category: 'rewards',
    group: '收藏品',
    title: 'Blook 圖鑑',
    description: '平台可用的角色收藏品',
  },
  avatar_frames: {
    category: 'rewards',
    group: '收藏品',
    title: '頭像框圖鑑',
    description: '平台可用的頭像框',
  },
  user_blooks: {
    category: 'rewards',
    group: '收藏品',
    title: 'Blook 持有紀錄',
    description: '已記錄的角色收藏持有情形',
  },
  user_frames: {
    category: 'rewards',
    group: '收藏品',
    title: '頭像框持有紀錄',
    description: '已記錄的頭像框持有情形',
  },
  achievement_definitions: {
    category: 'rewards',
    group: '成就',
    title: '成就設定',
    description: '成就的定義與設定',
  },
  achievement_progress: {
    category: 'rewards',
    group: '成就',
    title: '成就進度',
    description: '已記錄的成就累積進度',
  },
  achievement_unlocks: {
    category: 'rewards',
    group: '成就',
    title: '成就解鎖',
    description: '成就達成與解鎖紀錄',
  },
  profiles: {
    category: 'users',
    group: '帳號檔案',
    title: '帳號基本資料',
    description: '既有帳號檔案，個資依規則遮罩',
  },
};
